# Generated by Django 5.2.17 on 2026-10-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("demo_not_charged", "Not charged"),
                    ("paid", "Paid"),
                    ("refunded", "Refunded"),
                ],
                default="demo_not_charged",
                max_length=24,
            ),
        ),
    ]
